Added gamepad maping
dreamirl/dreamengine pull request #61
Opened 2024-08-09 16:13 UTC by GamaDu30

2024-08-09 16:28 UTC, Inateno requested changes

2024-08-09 16:28 UTC, Inateno commented on src/utils/gamepad.ts
> +  removeInputCallbacks(inputName: string) {
where this should be used and how? It looks like it doesn't remove the listeners but just remove from the Map.

2024-08-09 16:28 UTC, Inateno commented on src/utils/gamepad.ts
> +import Inputs, { InputType, default as InputsManager } from './Inputs';
why this ?

2024-08-13 08:55 UTC, liro-u requested changes

2024-08-13 08:55 UTC, liro-u commented on src/utils/gamepad.ts
> +import Inputs, { InputType } from './Inputs';
Need to keep previous naming to prevent compatibility with old project for update

2024-08-19 10:10 UTC, liro-u requested changes

2024-08-19 10:10 UTC, liro-u commented on src/utils/gamepad.ts
> +              if (this.inputs.dbInputs.GAMEPADBUTTONS[key] == i) {
use inputsmanager

2024-08-19 13:39 UTC, liro-u approved these changes

2024-08-19 14:39 UTC, merged